server:
  port: 9007

logging:
  #file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.baidu: debug

spring:
  redis:
    host: 192.168.65.139
    port: 6379
    passord: root
#canal配置
canal:
  client:
    instances:
      # exmaple
      example:
        host: 192.168.65.139
        port: 11111
